PROTOCOL = 'https:'
DOMAIN = '//todo.pixegami.io'

ENDPOINT = f'{PROTOCOL}{DOMAIN}'
INVALID_ENDPOINT = f'{PROTOCOL}{DOMAIN}/invalid'
ENDPOINT_CREATE_TASK = f'{PROTOCOL}{DOMAIN}/create-task'
ENDPOINT_UPDATE_TASK = f'{PROTOCOL}{DOMAIN}/update-task'
ENDPOINT_GET_TASK = f'{PROTOCOL}{DOMAIN}/get-task'
